### ISSUE TITLE
Issue with Technetium2019 solution

### ISSUE THREAD

**Issue by samtholiya** [Tosha1409/Codilitychallenges#1]
https://github.com/Tosha1409/Codilitychallenges/blob/157e54a3dc0f827999888405a2d02ab495ac21bf/Technetium2019.py#L1

print(solution([
    [9,9,4],
    [5,4,2],
    [5,4,5],
    [9,5,2]
]))
output: 994452 sum equals 33
where as
expected output should be
955952  = 35

**Comment by Tosha1409** [comment]
That's interesting case... surprised that it wasn't covered with tests, cause thats looks correct. I will try to fix it in nearest future

**Comment by Tosha1409** [comment]
I was checking it around week ago and forgot to reply here..

Actually solution is correct, because result is "sequence of cells that we should pick to obtain the biggest possible integer", not just sum of numbers, and this means that 994452 is not 9+9+4+4+5+2=33, but rather '9'+'9'+'4'+'4'+'5'+'2', or just simple '994452'.

And 994452>955952.
